package com.mapbox.services.android.navigation.v5.navigation;

import android.content.Context;
import android.location.Location;
import android.os.Build;

import com.mapbox.android.telemetry.AppUserTurnstile;
import com.mapbox.android.telemetry.Event;
import com.mapbox.android.telemetry.FeedbackData;
import com.mapbox.android.telemetry.FeedbackEventData;
import com.mapbox.android.telemetry.MapboxTelemetry;
import com.mapbox.android.telemetry.NavigationCancelData;
import com.mapbox.android.telemetry.NavigationEventFactory;
import com.mapbox.android.telemetry.NavigationLocationData;
import com.mapbox.android.telemetry.NavigationMetadata;
import com.mapbox.android.telemetry.NavigationNewData;
import com.mapbox.android.telemetry.NavigationRerouteData;
import com.mapbox.android.telemetry.NavigationState;
import com.mapbox.android.telemetry.NavigationStepMetadata;
import com.mapbox.android.telemetry.NavigationVoiceData;
import com.mapbox.services.android.navigation.BuildConfig;
import com.mapbox.services.android.navigation.v5.navigation.metrics.RerouteEvent;
import com.mapbox.services.android.navigation.v5.navigation.metrics.SessionState;
import com.mapbox.services.android.navigation.v5.routeprogress.MetricsRouteProgress;
import com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress;
import com.mapbox.services.android.navigation.v5.utils.DistanceUtils;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

final class NavigationMetricsWrapper {

  static String sdkIdentifier;
  private static String upcomingInstruction;
  private static String previousInstruction;
  private static String upcomingModifier;
  private static String previousModifier;
  private static String upcomingType;
  private static String upcomingName;
  private static String previousType;
  private static String previousName;
  // TODO Where are we going to create MapboxTelemetry instance? Which class is going to hold it?
  private static MapboxTelemetry mapboxTelemetry;

  private NavigationMetricsWrapper() {
    // Empty private constructor for preventing initialization of this class.
  }

  static void init(Context context, String accessToken, String userAgent) {
    mapboxTelemetry = new MapboxTelemetry(context, accessToken, userAgent);
    mapboxTelemetry.enable();
  }

  static void disable() {
    mapboxTelemetry.disable();
  }

  static void arriveEvent(SessionState sessionState, RouteProgress routeProgress, Location location) {
    NavigationEventFactory factory = new NavigationEventFactory();
    // TODO We should generate the Nav event spec version somehow. Should be managed and generated by the Events
    // library?
    int hardcodedEventVersion = 7;
    // TODO This should be managed and created by the Events library
    String device = Build.MODEL;
    MetricsRouteProgress metricsRouteProgress = new MetricsRouteProgress(routeProgress);
    int absoluteDistanceToDestination = DistanceUtils.calculateAbsoluteDistance(location, metricsRouteProgress);
    NavigationMetadata metadata = new NavigationMetadata(
      sessionState.startTimestamp(),
      (int) (sessionState.eventRouteDistanceCompleted() + routeProgress.distanceTraveled()),
      (int) routeProgress.distanceRemaining(),
      (int) routeProgress.durationRemaining(),
      sdkIdentifier,
      BuildConfig.MAPBOX_NAVIGATION_VERSION_NAME,
      hardcodedEventVersion,
      sessionState.sessionIdentifier(),
      location.getLatitude(),
      location.getLongitude(),
      sessionState.currentGeometry(),
      routeProgress.directionsRoute().routeOptions().profile(),
      sessionState.mockLocation(),
      device,
      sessionState.locationEngineName(),
      absoluteDistanceToDestination
    );
    metadata.setEstimatedDistance(routeProgress.directionsRoute().distance().intValue());
    metadata.setEstimatedDuration(routeProgress.directionsRoute().duration().intValue());
    metadata.setRerouteCount(sessionState.rerouteCount());
    metadata.setOriginalRequestIdentifier(sessionState.originalRequestIdentifier());
    metadata.setRequestIdentifier(sessionState.requestIdentifier());
    metadata.setOriginalGeometry(sessionState.originalGeometry());
    metadata.setOriginalEstimatedDistance(sessionState.originalDistance());
    metadata.setOriginalEstimatedDuration(sessionState.originalDuration());
    // TODO Check NavigationUtils.obtainAudioType(Context)
    // Should be managed and generated by the Events library?
    metadata.setAudioType("Use NavigationUtils#obtainAudioType(Context)");
    metadata.setStepCount(sessionState.currentStepCount());
    metadata.setOriginalStepCount(sessionState.originalStepCount());
    metadata.setPercentTimeInForeground(sessionState.percentInForeground());
    metadata.setPercentTimeInPortrait(sessionState.percentInPortrait());
    // TODO Check MAS 2.x TelemetryUtils#getVolumeLevel(Context)
    int hardcodedVolumeLevel = 99;
    metadata.setVolumeLevel(hardcodedVolumeLevel);
    // TODO Check MAS 2.x TelemetryUtils#getScreenBrightness(Context)
    int hardcodedScreenBrightness = 99;
    metadata.setScreenBrightness(hardcodedScreenBrightness);
    // TODO Check MAS 2.x TelemetryUtils#getApplicationState(Context)
    metadata.setApplicationState("Hardcoded application state");
    // TODO Check MAS 2.x MapboxTelemetry#isPluggedIn()
    boolean hardcodedBatteryPluggedIn = true;
    metadata.setBatteryPluggedIn(hardcodedBatteryPluggedIn);
    // TODO Check MAS 2.x MapboxTelemetry#getBatteryLevel()
    int hardcodedBatteryLevel = 99;
    metadata.setBatteryLevel(hardcodedBatteryLevel);
    // TODO Check MAS 2.x TelemetryUtils#getCellularNetworkType(Context)
    metadata.setConnectivity("Hardcoded connectivity");
    NavigationState state = new NavigationState(metadata);
    Event arriveEvent = factory.createNavigationEvent(Event.Type.NAV_ARRIVE, state);
    mapboxTelemetry.push(arriveEvent);
  }

  static void cancelEvent(SessionState sessionState, MetricsRouteProgress metricProgress, Location location) {
    // TODO We should generate the Nav event spec version somehow. Should be managed and generated by the Events
    // library?
    int hardcodedEventVersion = 7;
    // TODO This should be managed and created by the Events library
    String device = Build.MODEL;
    int absoluteDistanceToDestination = DistanceUtils.calculateAbsoluteDistance(location, metricProgress);
    NavigationMetadata metadata = new NavigationMetadata(
      sessionState.startTimestamp(),
      (int) (sessionState.eventRouteDistanceCompleted() + metricProgress.getDistanceTraveled()),
      metricProgress.getDistanceRemaining(),
      metricProgress.getDurationRemaining(),
      sdkIdentifier,
      BuildConfig.MAPBOX_NAVIGATION_VERSION_NAME,
      hardcodedEventVersion,
      sessionState.sessionIdentifier(),
      location.getLatitude(),
      location.getLongitude(),
      sessionState.currentGeometry(),
      metricProgress.getDirectionsRouteProfile(),
      sessionState.mockLocation(),
      device,
      sessionState.locationEngineName(),
      absoluteDistanceToDestination
    );
    metadata.setEstimatedDistance(metricProgress.getDirectionsRouteDistance());
    metadata.setEstimatedDuration(metricProgress.getDirectionsRouteDuration());
    metadata.setRerouteCount(sessionState.rerouteCount());
    metadata.setOriginalRequestIdentifier(sessionState.originalRequestIdentifier());
    metadata.setRequestIdentifier(sessionState.requestIdentifier());
    metadata.setOriginalGeometry(sessionState.originalGeometry());
    metadata.setOriginalEstimatedDistance(sessionState.originalDistance());
    metadata.setOriginalEstimatedDuration(sessionState.originalDuration());
    // TODO Check NavigationUtils.obtainAudioType(Context)
    // Should be managed and generated by the Events library?
    metadata.setAudioType("Use NavigationUtils#obtainAudioType(Context)");
    metadata.setStepCount(sessionState.currentStepCount());
    metadata.setOriginalStepCount(sessionState.originalStepCount());
    metadata.setPercentTimeInForeground(sessionState.percentInForeground());
    metadata.setPercentTimeInPortrait(sessionState.percentInPortrait());
    // TODO Check MAS 2.x TelemetryUtils#getVolumeLevel(Context)
    int hardcodedVolumeLevel = 99;
    metadata.setVolumeLevel(hardcodedVolumeLevel);
    // TODO Check MAS 2.x TelemetryUtils#getScreenBrightness(Context)
    int hardcodedScreenBrightness = 99;
    metadata.setScreenBrightness(hardcodedScreenBrightness);
    // TODO Check MAS 2.x TelemetryUtils#getApplicationState(Context)
    metadata.setApplicationState("Hardcoded application state");
    // TODO Check MAS 2.x MapboxTelemetry#isPluggedIn()
    boolean hardcodedBatteryPluggedIn = true;
    metadata.setBatteryPluggedIn(hardcodedBatteryPluggedIn);
    // TODO Check MAS 2.x MapboxTelemetry#getBatteryLevel()
    int hardcodedBatteryLevel = 99;
    metadata.setBatteryLevel(hardcodedBatteryLevel);
    // TODO Check MAS 2.x TelemetryUtils#getCellularNetworkType(Context)
    metadata.setConnectivity("Hardcoded connectivity");
    NavigationState state = new NavigationState(metadata);
    // TODO Check implementation
    // arrivalTimestamp could be null
    Date arrivalDate = sessionState.arrivalTimestamp();
    if (arrivalDate != null) {
      final String dateAndTimePattern = "yyyy-MM-dd'T'HH:mm:ss.SSSZ";
      final SimpleDateFormat dateFormat = new SimpleDateFormat(dateAndTimePattern, Locale.US);
      String arrivalTimestamp = dateFormat.format(arrivalDate);
      NavigationCancelData data = new NavigationCancelData(arrivalTimestamp);
      state.setNavigationCancelData(data);
    } else {
      NavigationCancelData data = new NavigationCancelData(null);
      state.setNavigationCancelData(data);
    }
    NavigationEventFactory factory = new NavigationEventFactory();
    Event cancelEvent = factory.createNavigationEvent(Event.Type.NAV_CANCEL, state);
    mapboxTelemetry.push(cancelEvent);
  }

  static void departEvent(SessionState sessionState, MetricsRouteProgress metricProgress, Location location) {
    NavigationEventFactory factory = new NavigationEventFactory();
    // TODO We should generate the Nav event spec version somehow. Should be managed and generated by the Events
    // library?
    int hardcodedEventVersion = 7;
    // TODO This should be managed and created by the Events library
    String device = Build.MODEL;
    int absoluteDistanceToDestination = DistanceUtils.calculateAbsoluteDistance(location, metricProgress);
    NavigationMetadata metadata = new NavigationMetadata(
      sessionState.startTimestamp(),
      metricProgress.getDistanceTraveled(),
      metricProgress.getDistanceRemaining(),
      metricProgress.getDurationRemaining(),
      sdkIdentifier,
      BuildConfig.MAPBOX_NAVIGATION_VERSION_NAME,
      hardcodedEventVersion,
      sessionState.sessionIdentifier(),
      location.getLatitude(),
      location.getLongitude(),
      sessionState.currentGeometry(),
      metricProgress.getDirectionsRouteProfile(),
      sessionState.mockLocation(),
      device,
      sessionState.locationEngineName(),
      absoluteDistanceToDestination
    );
    metadata.setEstimatedDistance(metricProgress.getDirectionsRouteDistance());
    metadata.setEstimatedDuration(metricProgress.getDirectionsRouteDuration());
    metadata.setRerouteCount(sessionState.rerouteCount());
    metadata.setOriginalRequestIdentifier(sessionState.originalRequestIdentifier());
    metadata.setRequestIdentifier(sessionState.requestIdentifier());
    metadata.setOriginalGeometry(sessionState.originalGeometry());
    metadata.setOriginalEstimatedDistance(sessionState.originalDistance());
    metadata.setOriginalEstimatedDuration(sessionState.originalDuration());
    // TODO Check NavigationUtils.obtainAudioType(Context)
    // Should be managed and generated by the Events library?
    metadata.setAudioType("Use NavigationUtils#obtainAudioType(Context)");
    metadata.setStepCount(sessionState.currentStepCount());
    metadata.setOriginalStepCount(sessionState.originalStepCount());
    metadata.setPercentTimeInForeground(sessionState.percentInForeground());
    metadata.setPercentTimeInPortrait(sessionState.percentInPortrait());
    // TODO Check MAS 2.x TelemetryUtils#getVolumeLevel(Context)
    int hardcodedVolumeLevel = 99;
    metadata.setVolumeLevel(hardcodedVolumeLevel);
    // TODO Check MAS 2.x TelemetryUtils#getScreenBrightness(Context)
    int hardcodedScreenBrightness = 99;
    metadata.setScreenBrightness(hardcodedScreenBrightness);
    // TODO Check MAS 2.x TelemetryUtils#getApplicationState(Context)
    metadata.setApplicationState("Hardcoded application state");
    // TODO Check MAS 2.x MapboxTelemetry#isPluggedIn()
    boolean hardcodedBatteryPluggedIn = true;
    metadata.setBatteryPluggedIn(hardcodedBatteryPluggedIn);
    // TODO Check MAS 2.x MapboxTelemetry#getBatteryLevel()
    int hardcodedBatteryLevel = 99;
    metadata.setBatteryLevel(hardcodedBatteryLevel);
    // TODO Check MAS 2.x TelemetryUtils#getCellularNetworkType(Context)
    metadata.setConnectivity("Hardcoded connectivity");
    NavigationState state = new NavigationState(metadata);
    Event departEvent = factory.createNavigationEvent(Event.Type.NAV_DEPART, state);
    mapboxTelemetry.push(departEvent);
  }

  static void rerouteEvent(RerouteEvent rerouteEvent, MetricsRouteProgress metricProgress,
                           Location location) {

    SessionState sessionState = rerouteEvent.getSessionState();
    // TODO We should generate the Nav event spec version somehow. Should be managed and generated by the Events
    // library?
    int hardcodedEventVersion = 7;
    // TODO This should be managed and created by the Events library
    String device = Build.MODEL;
    int absoluteDistanceToDestination = DistanceUtils.calculateAbsoluteDistance(location, metricProgress);
    NavigationMetadata metadata = new NavigationMetadata(
      sessionState.startTimestamp(),
      (int) sessionState.eventRouteDistanceCompleted(),
      sessionState.eventRouteProgress().getDistanceRemaining(),
      sessionState.eventRouteProgress().getDurationRemaining(),
      sdkIdentifier,
      BuildConfig.MAPBOX_NAVIGATION_VERSION_NAME,
      hardcodedEventVersion,
      sessionState.sessionIdentifier(),
      location.getLatitude(),
      location.getLongitude(),
      sessionState.currentGeometry(),
      metricProgress.getDirectionsRouteProfile(),
      sessionState.mockLocation(),
      device,
      sessionState.locationEngineName(),
      absoluteDistanceToDestination
    );
    metadata.setEstimatedDistance(metricProgress.getDirectionsRouteDistance());
    metadata.setEstimatedDuration(metricProgress.getDirectionsRouteDuration());
    metadata.setRerouteCount(sessionState.rerouteCount());
    metadata.setOriginalRequestIdentifier(sessionState.originalRequestIdentifier());
    metadata.setRequestIdentifier(sessionState.requestIdentifier());
    metadata.setOriginalGeometry(sessionState.originalGeometry());
    metadata.setOriginalEstimatedDistance(sessionState.originalDistance());
    metadata.setOriginalEstimatedDuration(sessionState.originalDuration());
    // TODO Check NavigationUtils.obtainAudioType(Context)
    // Should be managed and generated by the Events library?
    metadata.setAudioType("Use NavigationUtils#obtainAudioType(Context)");
    metadata.setStepCount(sessionState.currentStepCount());
    metadata.setOriginalStepCount(sessionState.originalStepCount());
    metadata.setPercentTimeInForeground(sessionState.percentInForeground());
    metadata.setPercentTimeInPortrait(sessionState.percentInPortrait());
    // TODO Check MAS 2.x TelemetryUtils#getVolumeLevel(Context)
    int hardcodedVolumeLevel = 99;
    metadata.setVolumeLevel(hardcodedVolumeLevel);
    // TODO Check MAS 2.x TelemetryUtils#getScreenBrightness(Context)
    int hardcodedScreenBrightness = 99;
    metadata.setScreenBrightness(hardcodedScreenBrightness);
    // TODO Check MAS 2.x TelemetryUtils#getApplicationState(Context)
    metadata.setApplicationState("Hardcoded application state");
    // TODO Check MAS 2.x MapboxTelemetry#isPluggedIn()
    boolean hardcodedBatteryPluggedIn = true;
    metadata.setBatteryPluggedIn(hardcodedBatteryPluggedIn);
    // TODO Check MAS 2.x MapboxTelemetry#getBatteryLevel()
    int hardcodedBatteryLevel = 99;
    metadata.setBatteryLevel(hardcodedBatteryLevel);
    // TODO Check MAS 2.x TelemetryUtils#getCellularNetworkType(Context)
    metadata.setConnectivity("Hardcoded connectivity");
    NavigationState state = new NavigationState(metadata);
    Location[] before = convertToArray(sessionState.beforeEventLocations());
    Location[] after = convertToArray(sessionState.afterEventLocations());
    NavigationLocationData locationData = new NavigationLocationData(before, after);
    state.setNavigationLocationData(locationData);
    int newDistanceRemaining = rerouteEvent.getNewDistanceRemaining();
    int newDurationRemaining = rerouteEvent.getNewDurationRemaining();
    String newGeometry = rerouteEvent.getNewRouteGeometry();
    NavigationNewData navigationNewData = new NavigationNewData(newDistanceRemaining, newDurationRemaining,
      newGeometry);
    int secondsSinceLastReroute = sessionState.secondsSinceLastReroute();
    NavigationRerouteData navigationRerouteData = new NavigationRerouteData(navigationNewData, secondsSinceLastReroute);
    state.setNavigationRerouteData(navigationRerouteData);
    // TODO Check MAS 2.x TelemetryUtils#buildUUID()
    String hardcodedFeedbackId = "Hardcoded feedback id";
    FeedbackData feedbackData = new FeedbackData(hardcodedFeedbackId);
    state.setFeedbackData(feedbackData);
    updateRouteProgressSessionData(metricProgress);
    NavigationStepMetadata navigationStepMetadata = new NavigationStepMetadata();
    navigationStepMetadata.setUpcomingInstruction(upcomingInstruction);
    navigationStepMetadata.setUpcomingType(upcomingType);
    navigationStepMetadata.setUpcomingModifier(upcomingModifier);
    navigationStepMetadata.setUpcomingName(upcomingName);
    navigationStepMetadata.setPreviousInstruction(previousInstruction);
    navigationStepMetadata.setPreviousType(previousType);
    navigationStepMetadata.setPreviousModifier(previousModifier);
    navigationStepMetadata.setPreviousName(previousName);
    int distance = metricProgress.getCurrentStepDistance();
    navigationStepMetadata.setDistance(distance);
    int duration = metricProgress.getCurrentStepDuration();
    navigationStepMetadata.setDuration(duration);
    int stepDistanceRemaining = metricProgress.getCurrentStepDistanceRemaining();
    navigationStepMetadata.setDistanceRemaining(stepDistanceRemaining);
    int stepDurationRemaining = metricProgress.getCurrentStepDurationRemaining();
    navigationStepMetadata.setDurationRemaining(stepDurationRemaining);
    state.setNavigationStepMetadata(navigationStepMetadata);
    // TODO Per new spec not needed anymore
    state.setNavigationVoiceData(new NavigationVoiceData(null, null));
    NavigationEventFactory factory = new NavigationEventFactory();
    Event navRerouteEvent = factory.createNavigationEvent(Event.Type.NAV_REROUTE, state);
    /* navRerouteEvent.put(MapboxNavigationEvent.KEY_CREATED, TelemetryUtils.generateCreateDate(location)); */
    // TODO We should expose a setter for created, in this case the value is coming from location.
    // Event? NavigationRerouteEvent?
    mapboxTelemetry.push(navRerouteEvent);
  }

  static void feedbackEvent(SessionState sessionState, MetricsRouteProgress metricProgress, Location location,
                            String description, String feedbackType, String screenshot, String feedbackId,
                            String vendorId) {
    // TODO We should generate the Nav event spec version somehow. Should be managed and generated by the Events
    // library?
    int hardcodedEventVersion = 7;
    // TODO This should be managed and created by the Events library
    String device = Build.MODEL;
    int absoluteDistanceToDestination = DistanceUtils.calculateAbsoluteDistance(location, metricProgress);
    NavigationMetadata metadata = new NavigationMetadata(
      sessionState.startTimestamp(),
      (int) sessionState.eventRouteDistanceCompleted(),
      sessionState.eventRouteProgress().getDistanceRemaining(),
      sessionState.eventRouteProgress().getDurationRemaining(),
      sdkIdentifier,
      BuildConfig.MAPBOX_NAVIGATION_VERSION_NAME,
      hardcodedEventVersion,
      sessionState.sessionIdentifier(),
      location.getLatitude(),
      location.getLongitude(),
      sessionState.currentGeometry(),
      metricProgress.getDirectionsRouteProfile(),
      sessionState.mockLocation(),
      device,
      sessionState.locationEngineName(),
      absoluteDistanceToDestination
    );
    metadata.setEstimatedDistance(metricProgress.getDirectionsRouteDistance());
    metadata.setEstimatedDuration(metricProgress.getDirectionsRouteDuration());
    metadata.setRerouteCount(sessionState.rerouteCount());
    metadata.setOriginalRequestIdentifier(sessionState.originalRequestIdentifier());
    metadata.setRequestIdentifier(sessionState.requestIdentifier());
    metadata.setOriginalGeometry(sessionState.originalGeometry());
    metadata.setOriginalEstimatedDistance(sessionState.originalDistance());
    metadata.setOriginalEstimatedDuration(sessionState.originalDuration());
    // TODO Check NavigationUtils.obtainAudioType(Context)
    // Should be managed and generated by the Events library?
    metadata.setAudioType("Use NavigationUtils#obtainAudioType(Context)");
    metadata.setStepCount(sessionState.currentStepCount());
    metadata.setOriginalStepCount(sessionState.originalStepCount());
    metadata.setPercentTimeInForeground(sessionState.percentInForeground());
    metadata.setPercentTimeInPortrait(sessionState.percentInPortrait());
    // TODO Check MAS 2.x TelemetryUtils#getVolumeLevel(Context)
    int hardcodedVolumeLevel = 99;
    metadata.setVolumeLevel(hardcodedVolumeLevel);
    // TODO Check MAS 2.x TelemetryUtils#getScreenBrightness(Context)
    int hardcodedScreenBrightness = 99;
    metadata.setScreenBrightness(hardcodedScreenBrightness);
    // TODO Check MAS 2.x TelemetryUtils#getApplicationState(Context)
    metadata.setApplicationState("Hardcoded application state");
    // TODO Check MAS 2.x MapboxTelemetry#isPluggedIn()
    boolean hardcodedBatteryPluggedIn = true;
    metadata.setBatteryPluggedIn(hardcodedBatteryPluggedIn);
    // TODO Check MAS 2.x MapboxTelemetry#getBatteryLevel()
    int hardcodedBatteryLevel = 99;
    metadata.setBatteryLevel(hardcodedBatteryLevel);
    // TODO Check MAS 2.x TelemetryUtils#getCellularNetworkType(Context)
    metadata.setConnectivity("Hardcoded connectivity");
    NavigationState state = new NavigationState(metadata);
    Location[] before = convertToArray(sessionState.beforeEventLocations());
    Location[] after = convertToArray(sessionState.afterEventLocations());
    NavigationLocationData locationData = new NavigationLocationData(before, after);
    state.setNavigationLocationData(locationData);
    FeedbackData feedbackData = new FeedbackData(feedbackId);
    feedbackData.setScreenshot(screenshot);
    state.setFeedbackData(feedbackData);
    updateRouteProgressSessionData(metricProgress);
    NavigationStepMetadata navigationStepMetadata = new NavigationStepMetadata();
    navigationStepMetadata.setUpcomingInstruction(upcomingInstruction);
    navigationStepMetadata.setUpcomingType(upcomingType);
    navigationStepMetadata.setUpcomingModifier(upcomingModifier);
    navigationStepMetadata.setUpcomingName(upcomingName);
    navigationStepMetadata.setPreviousInstruction(previousInstruction);
    navigationStepMetadata.setPreviousType(previousType);
    navigationStepMetadata.setPreviousModifier(previousModifier);
    navigationStepMetadata.setPreviousName(previousName);
    int distance = metricProgress.getCurrentStepDistance();
    navigationStepMetadata.setDistance(distance);
    int duration = metricProgress.getCurrentStepDuration();
    navigationStepMetadata.setDuration(duration);
    int stepDistanceRemaining = metricProgress.getCurrentStepDistanceRemaining();
    navigationStepMetadata.setDistanceRemaining(stepDistanceRemaining);
    int stepDurationRemaining = metricProgress.getCurrentStepDurationRemaining();
    navigationStepMetadata.setDurationRemaining(stepDurationRemaining);
    state.setNavigationStepMetadata(navigationStepMetadata);
    String userId = vendorId;
    // TODO Check MAS 2.x source is not currently sent
    String hardcodedSource = "Hardcoded source";
    // TODO Check MAS 2.x audio is not currently sent
    // From Navigation Telemetry Events V1 spec audio field is In discussion
    // Should we make it optional for now?
    String hardcodedAudio = "Hardcoded audio";
    FeedbackEventData feedbackEventData = new FeedbackEventData(userId, feedbackType, hardcodedSource, hardcodedAudio);
    feedbackEventData.setDescription(description);
    state.setFeedbackEventData(feedbackEventData);
    NavigationEventFactory factory = new NavigationEventFactory();
    Event feedbackEvent = factory.createNavigationEvent(Event.Type.NAV_FEEDBACK, state);
    /* navRerouteEvent.put(MapboxNavigationEvent.KEY_CREATED, TelemetryUtils.generateCreateDate(location)); */
    // TODO We should expose a setter for created, in this case the value is coming from location.
    // Event? NavigationRerouteEvent?
    mapboxTelemetry.push(feedbackEvent);
  }

  static Event turnstileEvent() {
    Event navTurnstileEvent = new AppUserTurnstile(sdkIdentifier,
      BuildConfig.MAPBOX_NAVIGATION_VERSION_NAME);
    return navTurnstileEvent;
  }

  private static void updateRouteProgressSessionData(MetricsRouteProgress routeProgress) {
    upcomingName = routeProgress.getUpcomingStepName();
    upcomingInstruction = routeProgress.getUpcomingStepInstruction();
    upcomingType = routeProgress.getUpcomingStepType();
    upcomingModifier = routeProgress.getUpcomingStepModifier();
    previousInstruction = routeProgress.getPreviousStepInstruction();
    previousType = routeProgress.getPreviousStepType();
    previousModifier = routeProgress.getPreviousStepModifier();
    previousName = routeProgress.getPreviousStepName();
  }

  private static Location[] convertToArray(List<Location> locationList) {
    return locationList.toArray(new Location[locationList.size()]);
  }
}
